/**
 * Mapiranje mjesta (općina/gradova) Hrvatske u pripadajuće županije.
 * Paralelno backend mapiranju u wp-plugin/cargo/includes/class-cargo-places.php
 *
 * Vrijednost je array radi rijetkih slučajeva istog imena u dvije županije
 * (npr. "Otok" postoji u Vukovarsko-srijemskoj i Splitsko-dalmatinskoj).
 */
export const PLACE_TO_COUNTIES: Record<string, string[]> = {
  'Andrijaševci':       ['Vukovarsko-srijemska'],
  'Antunovac':          ['Osječko-baranjska'],
  'Babina Greda':       ['Vukovarsko-srijemska'],
  'Bakar':              ['Primorsko-goranska'],
  'Bale-Valle':         ['Istarska županija'],
  'Barban':             ['Istarska županija'],
  'Barilović':          ['Karlovačka županija'],
  'Baška':              ['Primorsko-goranska'],
  'Baška Voda':         ['Splitsko-dalmatinska'],
  'Bebrina':            ['Brodsko-posavska'],
  'Bedekovčina':        ['Krapinsko-zagorska'],
  'Bedenica':           ['Zagrebačka županija'],
  'Bednja':             ['Varaždinska županija'],
  'Beli Manastir':      ['Osječko-baranjska'],
  'Belica':             ['Međimurska županija'],
  'Belišće':            ['Osječko-baranjska'],
  'Benkovac':           ['Zadarska županija'],
  'Berek':              ['Bjelovarsko-bilogorska'],
  'Beretinec':          ['Varaždinska županija'],
  'Bibinje':            ['Zadarska županija'],
  'Bilice':             ['Šibensko-kninska'],
  'Bilje':              ['Osječko-baranjska'],
  'Biograd na Moru':    ['Zadarska županija'],
  'Biskupija':          ['Šibensko-kninska'],
  'Bistra':             ['Zagrebačka županija'],
  'Bizovac':            ['Osječko-baranjska'],
  'Bjelovar':           ['Bjelovarsko-bilogorska'],
  'Blato':              ['Dubrovačko-neretvanska'],
  'Bogdanovci':         ['Vukovarsko-srijemska'],
  'Bol':                ['Splitsko-dalmatinska'],
  'Borovo':             ['Vukovarsko-srijemska'],
  'Bosiljevo':          ['Karlovačka županija'],
  'Bošnjaci':           ['Vukovarsko-srijemska'],
  'Brckovljani':        ['Zagrebačka županija'],
  'Brdovec':            ['Zagrebačka županija'],
  'Brela':              ['Splitsko-dalmatinska'],
  'Brestovac':          ['Požeško-slavonska'],
  'Breznica':           ['Varaždinska županija'],
  'Breznički Hum':      ['Varaždinska županija'],
  'Brinje':             ['Ličko-senjska'],
  'Brod Moravice':      ['Primorsko-goranska'],
  'Brodski Stupnik':    ['Brodsko-posavska'],
  'Brtonigla-Verteneglio': ['Istarska županija'],
  'Budinščina':         ['Krapinsko-zagorska'],
  'Buje-Buie':          ['Istarska županija'],
  'Bukovlje':           ['Brodsko-posavska'],
  'Buzet':              ['Istarska županija'],
  'Cerna':              ['Vukovarsko-srijemska'],
  'Cernik':             ['Brodsko-posavska'],
  'Cerovlje':           ['Istarska županija'],
  'Cestica':            ['Varaždinska županija'],
  'Cetingrad':          ['Karlovačka županija'],
  'Cista Provo':        ['Splitsko-dalmatinska'],
  'Civljane':           ['Šibensko-kninska'],
  'Cres':               ['Primorsko-goranska'],
  'Crikvenica':         ['Primorsko-goranska'],
  'Crnac':              ['Virovitičko-podravska'],
  'Čabar':              ['Primorsko-goranska'],
  'Čačinci':            ['Virovitičko-podravska'],
  'Čađavica':           ['Virovitičko-podravska'],
  'Čaglin':             ['Požeško-slavonska'],
  'Čakovec':            ['Međimurska županija'],
  'Čavle':              ['Primorsko-goranska'],
  'Čazma':              ['Bjelovarsko-bilogorska'],
  'Čeminac':            ['Osječko-baranjska'],
  'Čepin':              ['Osječko-baranjska'],
  'Darda':              ['Osječko-baranjska'],
  'Daruvar':            ['Bjelovarsko-bilogorska'],
  'Davor':              ['Brodsko-posavska'],
  'Dekanovec':          ['Međimurska županija'],
  'Delnice':            ['Primorsko-goranska'],
  'Desinić':            ['Krapinsko-zagorska'],
  'Dežanovac':          ['Bjelovarsko-bilogorska'],
  'Dicmo':              ['Splitsko-dalmatinska'],
  'Dobrinj':            ['Primorsko-goranska'],
  'Domašinec':          ['Međimurska županija'],
  'Donja Dubrava':      ['Međimurska županija'],
  'Donja Motičina':     ['Osječko-baranjska'],
  'Donja Stubica':      ['Krapinsko-zagorska'],
  'Donja Voća':         ['Varaždinska županija'],
  'Donji Andrijevci':   ['Brodsko-posavska'],
  'Donji Kraljevec':    ['Međimurska županija'],
  'Donji Kukuruzari':   ['Sisačko-moslavačka'],
  'Donji Lapac':        ['Ličko-senjska'],
  'Donji Miholjac':     ['Osječko-baranjska'],
  'Donji Vidovec':      ['Međimurska županija'],
  'Dragalić':           ['Brodsko-posavska'],
  'Draganić':           ['Karlovačka županija'],
  'Draž':               ['Osječko-baranjska'],
  'Drenovci':           ['Vukovarsko-srijemska'],
  'Drenje':             ['Osječko-baranjska'],
  'Drniš':              ['Šibensko-kninska'],
  'Drnje':              ['Koprivničko-križevačka'],
  'Dubrava':            ['Zagrebačka županija'],
  'Dubravica':          ['Zagrebačka županija'],
  'Dubrovačko primorje': ['Dubrovačko-neretvanska'],
  'Dubrovnik':          ['Dubrovačko-neretvanska'],
  'Duga Resa':          ['Karlovačka županija'],
  'Dugi Rat':           ['Splitsko-dalmatinska'],
  'Dugo Selo':          ['Zagrebačka županija'],
  'Dugopolje':          ['Splitsko-dalmatinska'],
  'Dvor':               ['Sisačko-moslavačka'],
  'Đakovo':             ['Osječko-baranjska'],
  'Đelekovec':          ['Koprivničko-križevačka'],
  'Đulovac':            ['Bjelovarsko-bilogorska'],
  'Đurđenovac':         ['Osječko-baranjska'],
  'Đurđevac':           ['Koprivničko-križevačka'],
  'Đurmanec':           ['Krapinsko-zagorska'],
  'Erdut':              ['Osječko-baranjska'],
  'Ernestinovo':        ['Osječko-baranjska'],
  'Ervenik':            ['Šibensko-kninska'],
  'Farkaševac':         ['Zagrebačka županija'],
  'Fažana-Fasana':      ['Istarska županija'],
  'Ferdinandovac':      ['Koprivničko-križevačka'],
  'Feričanci':          ['Osječko-baranjska'],
  'Funtana-Fontane':    ['Istarska županija'],
  'Fužine':             ['Primorsko-goranska'],
  'Galovac':            ['Zadarska županija'],
  'Garčin':             ['Brodsko-posavska'],
  'Garešnica':          ['Bjelovarsko-bilogorska'],
  'Generalski Stol':    ['Karlovačka županija'],
  'Glina':              ['Sisačko-moslavačka'],
  'Gola':               ['Koprivničko-križevačka'],
  'Goričan':            ['Međimurska županija'],
  'Gorjani':            ['Osječko-baranjska'],
  'Gornja Rijeka':      ['Koprivničko-križevačka'],
  'Gornja Stubica':     ['Krapinsko-zagorska'],
  'Gornja Vrba':        ['Brodsko-posavska'],
  'Gornji Bogićevci':   ['Brodsko-posavska'],
  'Gornji Kneginec':    ['Varaždinska županija'],
  'Gornji Mihaljevec':  ['Međimurska županija'],
  'Gospić':             ['Ličko-senjska'],
  'Gračac':             ['Zadarska županija'],
  'Gračišće':           ['Istarska županija'],
  'Grad Zagreb':        ['Grad Zagreb'],
  'Gradac':             ['Splitsko-dalmatinska'],
  'Gradec':             ['Zagrebačka županija'],
  'Gradina':            ['Virovitičko-podravska'],
  'Gradište':           ['Vukovarsko-srijemska'],
  'Grožnjan-Grisignana': ['Istarska županija'],
  'Grubišno Polje':     ['Bjelovarsko-bilogorska'],
  'Gundinci':           ['Brodsko-posavska'],
  'Gunja':              ['Vukovarsko-srijemska'],
  'Gvozd':              ['Sisačko-moslavačka'],
  'Hercegovac':         ['Bjelovarsko-bilogorska'],
  'Hlebine':            ['Koprivničko-križevačka'],
  'Hrašćina':           ['Krapinsko-zagorska'],
  'Hrvace':             ['Splitsko-dalmatinska'],
  'Hrvatska Dubica':    ['Sisačko-moslavačka'],
  'Hrvatska Kostajnica': ['Sisačko-moslavačka'],
  'Hum na Sutli':       ['Krapinsko-zagorska'],
  'Hvar':               ['Splitsko-dalmatinska'],
  'Ilok':               ['Vukovarsko-srijemska'],
  'Imotski':            ['Splitsko-dalmatinska'],
  'Ivanec':             ['Varaždinska županija'],
  'Ivanić-Grad':        ['Zagrebačka županija'],
  'Ivankovo':           ['Vukovarsko-srijemska'],
  'Ivanska':            ['Bjelovarsko-bilogorska'],
  'Jagodnjak':          ['Osječko-baranjska'],
  'Jakovlje':           ['Zagrebačka županija'],
  'Jakšić':             ['Požeško-slavonska'],
  'Jalžabet':           ['Varaždinska županija'],
  'Janjina':            ['Dubrovačko-neretvanska'],
  'Jarmina':            ['Vukovarsko-srijemska'],
  'Jasenice':           ['Zadarska županija'],
  'Jasenovac':          ['Sisačko-moslavačka'],
  'Jastrebarsko':       ['Zagrebačka županija'],
  'Jelenje':            ['Primorsko-goranska'],
  'Jelsa':              ['Splitsko-dalmatinska'],
  'Jesenje':            ['Krapinsko-zagorska'],
  'Josipdol':           ['Karlovačka županija'],
  'Kali':               ['Zadarska županija'],
  'Kalinovac':          ['Koprivničko-križevačka'],
  'Kalnik':             ['Koprivničko-križevačka'],
  'Kamanje':            ['Karlovačka županija'],
  'Kanfanar':           ['Istarska županija'],
  'Kapela':             ['Bjelovarsko-bilogorska'],
  'Kaptol':             ['Požeško-slavonska'],
  'Karlobag':           ['Ličko-senjska'],
  'Karlovac':           ['Karlovačka županija'],
  'Karojba':            ['Istarska županija'],
  'Kastav':             ['Primorsko-goranska'],
  'Kaštela':            ['Splitsko-dalmatinska'],
  'Kaštelir-Labinci-Castelliere-S. Domenica': ['Istarska županija'],
  'Kijevo':             ['Šibensko-kninska'],
  'Kistanje':           ['Šibensko-kninska'],
  'Klakar':             ['Brodsko-posavska'],
  'Klana':              ['Primorsko-goranska'],
  'Klanjec':            ['Krapinsko-zagorska'],
  'Klenovnik':          ['Varaždinska županija'],
  'Klinča Sela':        ['Zagrebačka županija'],
  'Klis':               ['Splitsko-dalmatinska'],
  'Kloštar Ivanić':     ['Zagrebačka županija'],
  'Kloštar Podravski':  ['Koprivničko-križevačka'],
  'Kneževi Vinogradi':  ['Osječko-baranjska'],
  'Knin':               ['Šibensko-kninska'],
  'Kolan':              ['Zadarska županija'],
  'Komiža':             ['Splitsko-dalmatinska'],
  'Konavle':            ['Dubrovačko-neretvanska'],
  'Končanica':          ['Bjelovarsko-bilogorska'],
  'Konjščina':          ['Krapinsko-zagorska'],
  'Koprivnica':         ['Koprivničko-križevačka'],
  'Koprivnički Bregi':  ['Koprivničko-križevačka'],
  'Koprivnički Ivanec': ['Koprivničko-križevačka'],
  'Korčula':            ['Dubrovačko-neretvanska'],
  'Kostrena':           ['Primorsko-goranska'],
  'Koška':              ['Osječko-baranjska'],
  'Kotoriba':           ['Međimurska županija'],
  'Kraljevec na Sutli': ['Krapinsko-zagorska'],
  'Kraljevica':         ['Primorsko-goranska'],
  'Krapina':            ['Krapinsko-zagorska'],
  'Krapinske Toplice':  ['Krapinsko-zagorska'],
  'Krašić':             ['Zagrebačka županija'],
  'Kravarsko':          ['Zagrebačka županija'],
  'Križ':               ['Zagrebačka županija'],
  'Križevci':           ['Koprivničko-križevačka'],
  'Krk':                ['Primorsko-goranska'],
  'Krnjak':             ['Karlovačka županija'],
  'Kršan':              ['Istarska županija'],
  'Kukljica':           ['Zadarska županija'],
  'Kula Norinska':      ['Dubrovačko-neretvanska'],
  'Kumrovec':           ['Krapinsko-zagorska'],
  'Kutina':             ['Sisačko-moslavačka'],
  'Kutjevo':            ['Požeško-slavonska'],
  'Labin':              ['Istarska županija'],
  'Lanišće':            ['Istarska županija'],
  'Lasinja':            ['Karlovačka županija'],
  'Lastovo':            ['Dubrovačko-neretvanska'],
  'Lećevica':           ['Splitsko-dalmatinska'],
  'Legrad':             ['Koprivničko-križevačka'],
  'Lekenik':            ['Sisačko-moslavačka'],
  'Lepoglava':          ['Varaždinska županija'],
  'Levanjska Varoš':    ['Osječko-baranjska'],
  'Lipik':              ['Požeško-slavonska'],
  'Lipovljani':         ['Sisačko-moslavačka'],
  'Lišane Ostrovičke':  ['Zadarska županija'],
  'Ližnjan-Lisignano':  ['Istarska županija'],
  'Lobor':              ['Krapinsko-zagorska'],
  'Lokve':              ['Primorsko-goranska'],
  'Lokvičići':          ['Splitsko-dalmatinska'],
  'Lopar':              ['Primorsko-goranska'],
  'Lovas':              ['Vukovarsko-srijemska'],
  'Lovinac':            ['Ličko-senjska'],
  'Lovran':             ['Primorsko-goranska'],
  'Lovreć':             ['Splitsko-dalmatinska'],
  'Ludbreg':            ['Varaždinska županija'],
  'Luka':               ['Zagrebačka županija'],
  'Lukač':              ['Virovitičko-podravska'],
  'Lumbarda':           ['Dubrovačko-neretvanska'],
  'Lupoglav':           ['Istarska županija'],
  'Ljubešćica':         ['Varaždinska županija'],
  'Mače':               ['Krapinsko-zagorska'],
  'Magadenovac':        ['Osječko-baranjska'],
  'Majur':              ['Sisačko-moslavačka'],
  'Makarska':           ['Splitsko-dalmatinska'],
  'Mala Subotica':      ['Međimurska županija'],
  'Mali Bukovec':       ['Varaždinska županija'],
  'Mali Lošinj':        ['Primorsko-goranska'],
  'Malinska-Dubašnica': ['Primorsko-goranska'],
  'Marčana':            ['Istarska županija'],
  'Marija Bistrica':    ['Krapinsko-zagorska'],
  'Marija Gorica':      ['Zagrebačka županija'],
  'Marijanci':          ['Osječko-baranjska'],
  'Marina':             ['Splitsko-dalmatinska'],
  'Markušica':          ['Vukovarsko-srijemska'],
  'Martijanec':         ['Varaždinska županija'],
  'Martinska Ves':      ['Sisačko-moslavačka'],
  'Maruševec':          ['Varaždinska županija'],
  'Matulji':            ['Primorsko-goranska'],
  'Medulin':            ['Istarska županija'],
  'Metković':           ['Dubrovačko-neretvanska'],
  'Mihovljan':          ['Krapinsko-zagorska'],
  'Mikleuš':            ['Virovitičko-podravska'],
  'Milna':              ['Splitsko-dalmatinska'],
  'Mljet':              ['Dubrovačko-neretvanska'],
  'Molve':              ['Koprivničko-križevačka'],
  'Mošćenička Draga':   ['Primorsko-goranska'],
  'Motovun-Montona':    ['Istarska županija'],
  'Mrkopalj':           ['Primorsko-goranska'],
  'Muć':                ['Splitsko-dalmatinska'],
  'Mursko Središće':    ['Međimurska županija'],
  'Murter-Kornati':     ['Šibensko-kninska'],
  'Našice':             ['Osječko-baranjska'],
  'Nedelišće':          ['Međimurska županija'],
  'Negoslavci':         ['Vukovarsko-srijemska'],
  'Nerežišća':          ['Splitsko-dalmatinska'],
  'Netretić':           ['Karlovačka županija'],
  'Nijemci':            ['Vukovarsko-srijemska'],
  'Nin':                ['Zadarska županija'],
  'Nova Bukovica':      ['Virovitičko-podravska'],
  'Nova Gradiška':      ['Brodsko-posavska'],
  'Nova Kapela':        ['Brodsko-posavska'],
  'Nova Rača':          ['Bjelovarsko-bilogorska'],
  'Novalja':            ['Ličko-senjska'],
  'Novi Golubovec':     ['Krapinsko-zagorska'],
  'Novi Marof':         ['Varaždinska županija'],
  'Novi Vinodolski':    ['Primorsko-goranska'],
  'Novigrad':           ['Zadarska županija'],
  'Novigrad Podravski': ['Koprivničko-križevačka'],
  'Novigrad-Cittanova': ['Istarska županija'],
  'Novo Virje':         ['Koprivničko-križevačka'],
  'Novska':             ['Sisačko-moslavačka'],
  'Nuštar':             ['Vukovarsko-srijemska'],
  'Obrovac':            ['Zadarska županija'],
  'Ogulin':             ['Karlovačka županija'],
  'Okrug':              ['Splitsko-dalmatinska'],
  'Okučani':            ['Brodsko-posavska'],
  'Omiš':               ['Splitsko-dalmatinska'],
  'Omišalj':            ['Primorsko-goranska'],
  'Opatija':            ['Primorsko-goranska'],
  'Oprisavci':          ['Brodsko-posavska'],
  'Oprtalj-Portole':    ['Istarska županija'],
  'Opuzen':             ['Dubrovačko-neretvanska'],
  'Orahovica':          ['Virovitičko-podravska'],
  'Orebić':             ['Dubrovačko-neretvanska'],
  'Orehovica':          ['Međimurska županija'],
  'Oriovac':            ['Brodsko-posavska'],
  'Orle':               ['Zagrebačka županija'],
  'Oroslavje':          ['Krapinsko-zagorska'],
  'Osijek':             ['Osječko-baranjska'],
  'Otočac':             ['Ličko-senjska'],
  'Otok':               ['Vukovarsko-srijemska', 'Splitsko-dalmatinska'],
  'Ozalj':              ['Karlovačka županija'],
  'Pag':                ['Zadarska županija'],
  'Pakoštane':          ['Zadarska županija'],
  'Pakrac':             ['Požeško-slavonska'],
  'Pašman':             ['Zadarska županija'],
  'Pazin':              ['Istarska županija'],
  'Perušić':            ['Ličko-senjska'],
  'Peteranec':          ['Koprivničko-križevačka'],
  'Petlovac':           ['Osječko-baranjska'],
  'Petrijanec':         ['Varaždinska županija'],
  'Petrijevci':         ['Osječko-baranjska'],
  'Petrinja':           ['Sisačko-moslavačka'],
  'Petrovsko':          ['Krapinsko-zagorska'],
  'Pićan':              ['Istarska županija'],
  'Pirovac':            ['Šibensko-kninska'],
  'Pisarovina':         ['Zagrebačka županija'],
  'Pitomača':           ['Virovitičko-podravska'],
  'Plaški':             ['Karlovačka županija'],
  'Pleternica':         ['Požeško-slavonska'],
  'Plitvička Jezera':   ['Ličko-senjska'],
  'Ploče':              ['Dubrovačko-neretvanska'],
  'Podbablje':          ['Splitsko-dalmatinska'],
  'Podcrkavlje':        ['Brodsko-posavska'],
  'Podgora':            ['Splitsko-dalmatinska'],
  'Podgorač':           ['Osječko-baranjska'],
  'Podravska Moslavina': ['Osječko-baranjska'],
  'Podravske Sesvete':  ['Koprivničko-križevačka'],
  'Podstrana':          ['Splitsko-dalmatinska'],
  'Podturen':           ['Međimurska županija'],
  'Pojezerje':          ['Dubrovačko-neretvanska'],
  'Pokupsko':           ['Zagrebačka županija'],
  'Polača':             ['Zadarska županija'],
  'Poličnik':           ['Zadarska županija'],
  'Popovac':            ['Osječko-baranjska'],
  'Popovača':           ['Sisačko-moslavačka'],
  'Poreč-Parenzo':      ['Istarska županija'],
  'Posedarje':          ['Zadarska županija'],
  'Postira':            ['Splitsko-dalmatinska'],
  'Povljana':           ['Zadarska županija'],
  'Požega':             ['Požeško-slavonska'],
  'Pregrada':           ['Krapinsko-zagorska'],
  'Preko':              ['Zadarska županija'],
  'Prelog':             ['Međimurska županija'],
  'Preseka':            ['Zagrebačka županija'],
  'Prgomet':            ['Splitsko-dalmatinska'],
  'Pribislavec':        ['Međimurska županija'],
  'Primorski Dolac':    ['Splitsko-dalmatinska'],
  'Primošten':          ['Šibensko-kninska'],
  'Privlaka':           ['Vukovarsko-srijemska', 'Zadarska županija'],
  'Proložac':           ['Splitsko-dalmatinska'],
  'Promina':            ['Šibensko-kninska'],
  'Pučišća':            ['Splitsko-dalmatinska'],
  'Pula-Pola':          ['Istarska županija'],
  'Punat':              ['Primorsko-goranska'],
  'Punitovci':          ['Osječko-baranjska'],
  'Pušća':              ['Zagrebačka županija'],
  'Rab':                ['Primorsko-goranska'],
  'Radoboj':            ['Krapinsko-zagorska'],
  'Rakovec':            ['Zagrebačka županija'],
  'Rakovica':           ['Karlovačka županija'],
  'Rasinja':            ['Koprivničko-križevačka'],
  'Raša':               ['Istarska županija'],
  'Ravna Gora':         ['Primorsko-goranska'],
  'Ražanac':            ['Zadarska županija'],
  'Rešetari':           ['Brodsko-posavska'],
  'Ribnik':             ['Karlovačka županija'],
  'Rijeka':             ['Primorsko-goranska'],
  'Rogoznica':          ['Šibensko-kninska'],
  'Rovinj-Rovigno':     ['Istarska županija'],
  'Rovišće':            ['Bjelovarsko-bilogorska'],
  'Rugvica':            ['Zagrebačka županija'],
  'Runovići':           ['Splitsko-dalmatinska'],
  'Ružić':              ['Šibensko-kninska'],
  'Saborsko':           ['Karlovačka županija'],
  'Sali':               ['Zadarska županija'],
  'Samobor':            ['Zagrebačka županija'],
  'Satnica Đakovačka':  ['Osječko-baranjska'],
  'Seget':              ['Splitsko-dalmatinska'],
  'Selca':              ['Splitsko-dalmatinska'],
  'Selnica':            ['Međimurska županija'],
  'Semeljci':           ['Osječko-baranjska'],
  'Senj':               ['Ličko-senjska'],
  'Severin':            ['Bjelovarsko-bilogorska'],
  'Sibinj':             ['Brodsko-posavska'],
  'Sikirevci':          ['Vukovarsko-srijemska'],
  'Sinj':               ['Splitsko-dalmatinska'],
  'Sirač':              ['Bjelovarsko-bilogorska'],
  'Sisak':              ['Sisačko-moslavačka'],
  'Skrad':              ['Primorsko-goranska'],
  'Skradin':            ['Šibensko-kninska'],
  'Slatina':            ['Virovitičko-podravska'],
  'Slavonski Brod':     ['Brodsko-posavska'],
  'Slavonski Šamac':    ['Brodsko-posavska'],
  'Slivno':             ['Dubrovačko-neretvanska'],
  'Slunj':              ['Karlovačka županija'],
  'Smokvica':           ['Dubrovačko-neretvanska'],
  'Sokolovac':          ['Koprivničko-križevačka'],
  'Solin':              ['Splitsko-dalmatinska'],
  'Sopje':              ['Virovitičko-podravska'],
  'Split':              ['Splitsko-dalmatinska'],
  'Sračinec':           ['Varaždinska županija'],
  'Stankovci':          ['Zadarska županija'],
  'Stara Gradiška':     ['Brodsko-posavska'],
  'Stari Grad':         ['Splitsko-dalmatinska'],
  'Stari Jankovci':     ['Vukovarsko-srijemska'],
  'Stari Mikanovci':    ['Vukovarsko-srijemska'],
  'Starigrad':          ['Zadarska županija'],
  'Staro Petrovo Selo': ['Brodsko-posavska'],
  'Ston':               ['Dubrovačko-neretvanska'],
  'Strahoninec':        ['Međimurska županija'],
  'Strizivojna':        ['Osječko-baranjska'],
  'Stubičke Toplice':   ['Krapinsko-zagorska'],
  'Stupnik':            ['Zagrebačka županija'],
  'Sućuraj':            ['Splitsko-dalmatinska'],
  'Suhopolje':          ['Virovitičko-podravska'],
  'Sukošan':            ['Zadarska županija'],
  'Sunja':              ['Sisačko-moslavačka'],
  'Supetar':            ['Splitsko-dalmatinska'],
  'Sutivan':            ['Splitsko-dalmatinska'],
  'Sveta Marija':       ['Međimurska županija'],
  'Sveta Nedjelja':     ['Zagrebačka županija', 'Splitsko-dalmatinska'],
  'Sveti Đurđ':         ['Varaždinska županija'],
  'Sveti Filip i Jakov': ['Zadarska županija'],
  'Sveti Ilija':        ['Varaždinska županija'],
  'Sveti Ivan Zelina':  ['Zagrebačka županija'],
  'Sveti Ivan Žabno':   ['Koprivničko-križevačka'],
  'Sveti Juraj na Bregu': ['Međimurska županija'],
  'Sveti Križ Začretje': ['Krapinsko-zagorska'],
  'Sveti Lovreč':       ['Istarska županija'],
  'Sveti Martin na Muri': ['Međimurska županija'],
  'Sveti Petar Orehovec': ['Koprivničko-križevačka'],
  'Sveti Petar u Šumi': ['Istarska županija'],
  'Svetvinčenat':       ['Istarska županija'],
  'Šandrovac':          ['Bjelovarsko-bilogorska'],
  'Šenkovec':           ['Međimurska županija'],
  'Šestanovac':         ['Splitsko-dalmatinska'],
  'Šibenik':            ['Šibensko-kninska'],
  'Škabrnja':           ['Zadarska županija'],
  'Šodolovci':          ['Osječko-baranjska'],
  'Šolta':              ['Splitsko-dalmatinska'],
  'Špišić Bukovica':    ['Virovitičko-podravska'],
  'Štefanje':           ['Bjelovarsko-bilogorska'],
  'Štitar':             ['Vukovarsko-srijemska'],
  'Štrigova':           ['Međimurska županija'],
  'Tar-Vabriga-Torre Abrega': ['Istarska županija'],
  'Tinjan':             ['Istarska županija'],
  'Tisno':              ['Šibensko-kninska'],
  'Tkon':               ['Zadarska županija'],
  'Tompojevci':         ['Vukovarsko-srijemska'],
  'Topusko':            ['Sisačko-moslavačka'],
  'Tordinci':           ['Vukovarsko-srijemska'],
  'Tounj':              ['Karlovačka županija'],
  'Tovarnik':           ['Vukovarsko-srijemska'],
  'Tribunj':            ['Šibensko-kninska'],
  'Trilj':              ['Splitsko-dalmatinska'],
  'Trnava':             ['Osječko-baranjska'],
  'Trnovec Bartolovečki': ['Varaždinska županija'],
  'Trogir':             ['Splitsko-dalmatinska'],
  'Trpanj':             ['Dubrovačko-neretvanska'],
  'Trpinja':            ['Vukovarsko-srijemska'],
  'Tučepi':             ['Splitsko-dalmatinska'],
  'Tuhelj':             ['Krapinsko-zagorska'],
  'Udbina':             ['Ličko-senjska'],
  'Umag-Umago':         ['Istarska županija'],
  'Unešić':             ['Šibensko-kninska'],
  'Valpovo':            ['Osječko-baranjska'],
  'Varaždin':           ['Varaždinska županija'],
  'Varaždinske Toplice': ['Varaždinska županija'],
  'Vela Luka':          ['Dubrovačko-neretvanska'],
  'Velika':             ['Požeško-slavonska'],
  'Velika Gorica':      ['Zagrebačka županija'],
  'Velika Kopanica':    ['Brodsko-posavska'],
  'Velika Ludina':      ['Sisačko-moslavačka'],
  'Velika Pisanica':    ['Bjelovarsko-bilogorska'],
  'Velika Trnovitica':  ['Bjelovarsko-bilogorska'],
  'Veliki Bukovec':     ['Varaždinska županija'],
  'Veliki Grđevac':     ['Bjelovarsko-bilogorska'],
  'Veliko Trgovišće':   ['Krapinsko-zagorska'],
  'Veliko Trojstvo':    ['Bjelovarsko-bilogorska'],
  'Vidovec':            ['Varaždinska županija'],
  'Viljevo':            ['Osječko-baranjska'],
  'Vinica':             ['Varaždinska županija'],
  'Vinkovci':           ['Vukovarsko-srijemska'],
  'Vinodolska općina':  ['Primorsko-goranska'],
  'Vir':                ['Zadarska županija'],
  'Virje':              ['Koprivničko-križevačka'],
  'Virovitica':         ['Virovitičko-podravska'],
  'Vis':                ['Splitsko-dalmatinska'],
  'Visoko':             ['Varaždinska županija'],
  'Viškovci':           ['Osječko-baranjska'],
  'Viškovo':            ['Primorsko-goranska'],
  'Višnjan-Visignano':  ['Istarska županija'],
  'Vižinada-Visinada':  ['Istarska županija'],
  'Vladislavci':        ['Osječko-baranjska'],
  'Voćin':              ['Virovitičko-podravska'],
  'Vodice':             ['Šibensko-kninska'],
  'Vodnjan-Dignano':    ['Istarska županija'],
  'Vođinci':            ['Vukovarsko-srijemska'],
  'Vojnić':             ['Karlovačka županija'],
  'Vratišinec':         ['Međimurska županija'],
  'Vrbanja':            ['Vukovarsko-srijemska'],
  'Vrbje':              ['Brodsko-posavska'],
  'Vrbnik':             ['Primorsko-goranska'],
  'Vrbovec':            ['Zagrebačka županija'],
  'Vrbovsko':           ['Primorsko-goranska'],
  'Vrgorac':            ['Splitsko-dalmatinska'],
  'Vrhovine':           ['Ličko-senjska'],
  'Vrlika':             ['Splitsko-dalmatinska'],
  'Vrpolje':            ['Brodsko-posavska'],
  'Vrsar-Orsera':       ['Istarska županija'],
  'Vrsi':               ['Zadarska županija'],
  'Vuka':               ['Osječko-baranjska'],
  'Vukovar':            ['Vukovarsko-srijemska'],
  'Zabok':              ['Krapinsko-zagorska'],
  'Zadar':              ['Zadarska županija'],
  'Zadvarje':           ['Splitsko-dalmatinska'],
  'Zagorska Sela':      ['Krapinsko-zagorska'],
  'Zagvozd':            ['Splitsko-dalmatinska'],
  'Zaprešić':           ['Zagrebačka županija'],
  'Zažablje':           ['Dubrovačko-neretvanska'],
  'Zdenci':             ['Virovitičko-podravska'],
  'Zemunik Donji':      ['Zadarska županija'],
  'Zlatar':             ['Krapinsko-zagorska'],
  'Zlatar Bistrica':    ['Krapinsko-zagorska'],
  'Zmijavci':           ['Splitsko-dalmatinska'],
  'Zrinski Topolovac':  ['Bjelovarsko-bilogorska'],
  'Žakanje':            ['Karlovačka županija'],
  'Žminj':              ['Istarska županija'],
  'Žumberak':           ['Zagrebačka županija'],
  'Župa dubrovačka':    ['Dubrovačko-neretvanska'],
  'Županja':            ['Vukovarsko-srijemska'],
};

/**
 * Vrati listu mjesta u zadanoj županiji (sortirana abecedno).
 * Ako je županija prazna, vraća sva mjesta.
 */
export function getPlacesByCounty(zupanija: string | null | undefined): string[] {
  const all = Object.keys(PLACE_TO_COUNTIES);
  if (!zupanija) return all.sort((a, b) => a.localeCompare(b, 'hr'));

  return all
    .filter(place => PLACE_TO_COUNTIES[place].includes(zupanija))
    .sort((a, b) => a.localeCompare(b, 'hr'));
}
